처리 추가

diff --git a/.github/workflows/lambda.yml b/.github/workflows/lambda.yml
--- a/.github/workflows/lambda.yml
+++ b/.github/workflows/lambda.yml
@@ -62,11 +62,17 @@ jobs:
             PROVISIONED=${{ inputs.provisioned_concurrency }}
           fi
 
-          IMAGE_DIGEST=$(aws ecr describe-images --repository-name ${{ inputs.name }} --image-ids imageTag=${{ inputs.version }} --query 'imageDetails[0].imageDigest' --output text)
+          SHA_IMAGE_DIGEST=$(aws ecr describe-images --repository-name ${{ inputs.name }} --image-ids imageTag=${{ inputs.version }} --query 'imageDetails[0].imageDigest' --output text)
 
+          if [ -z "$SHA_IMAGE_DIGEST" ]; then
+            echo "::error title=Image Not Found::ecr image not found"
+            exit 1
+          else
+            IMAGE_DIGEST=$(echo $SHA_IMAGE_DIGEST | cut -d ':' -f 2-)
+          fi
 
           echo "function_name=$FUNCTION_NAME" >> "$GITHUB_OUTPUT"
-          echo "image_digest=$(echo $IMAGE_DIGEST | cut -d ':' -f 2-)" >> "$GITHUB_OUTPUT"
+          echo "image_digest=$IMAGE_DIGEST" >> "$GITHUB_OUTPUT"
           echo "provisioned_concurrency=$PROVISIONED" >> "$GITHUB_OUTPUT"
           echo "role_session_name=$ROLE_SESSION_NAME" >> "$GITHUB_OUTPUT"
           echo "role_policy_name=$ROLE_REVOKE_POLICY" >> "$GITHUB_OUTPUT"
